fix service setup44

diff --git a/myportal/roles/nestjs-deploy/templates/nestjs-deploy.yml b/myportal/roles/nestjs-deploy/templates/nestjs-deploy.yml
--- a/myportal/roles/nestjs-deploy/templates/nestjs-deploy.yml
+++ b/myportal/roles/nestjs-deploy/templates/nestjs-deploy.yml
@@ -51,7 +51,7 @@ spec:
 
       containers:
         - name: { { portalname } }
-          image: ubuntu:latest
+          image: node:slim
           command:
             - /bin/bash
           args:
@@ -62,8 +62,8 @@ spec:
               cd /data || { echo "Failed to change directly to /data"; exit 1;}
               echo "Running application..."
               npm install || { echo "Failed to install dependencies"; exit 1; }
-        echo "Starting application..."
-        npm start || { echo "Failed to start application"; exit 1; }
+              echo "Starting application..."
+              npm start || { echo "Failed to start application"; exit 1; }
 
           env:
             - name: REDIS_HOST
